config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/list', to: 'sessions#list'
  get '/register', to: 'users#new'

  resources :users do
    post :sort, on: :collection
    get :email, on: :collection
    member do
      get 'list'
    end
  end

  resources :items, except: [:index, :show] do
    member do
      post :activate
    end
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user

  validates :body, presence: true, length: {minimum: 3}

  def self.to_db_time(dt)
    dt.in_time_zone("Pacific Time (US & Canada)")
  end


end

app/models/user.rb
require 'sluggable'

class User < ActiveRecord::Base

  include Sluggable

  has_many :items

  has_secure_password validations: false

  validates :username, presence: true, uniqueness: true
  validates :password, presence: true, on: :create, length: { minimum: 3 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?, :logged_in_as_creator?
  helper_method :user_time_zone_offset, :decimal_to_time_zone
  helper_method :current_user_has_phone

  def decimal_to_time_zone(deci)
    leading_sign='+'
    if deci.start_with?('+','-')
      leading_sign = deci.slice!(0)
    end
    hours_section = deci.split('.')[0].rjust(2, "0")
    minutes_section = deci.split('.')[1] == nil ? '00' : deci.split('.')[1].ljust(2, "0")
    leading_sign+hours_section+minutes_section
  end

  def logged_in?
    !!current_user
  end

  def current_user
    # if theres an authenticated user, return user object else nil
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    if !logged_in?
      flash[:error] = 'Must be logged in to do that.'
      redirect_to root_path
    end
  end

  def require_item_creator
    if current_user.id != @item.user_id
      access_denied
    end
  end

  def logged_in_as_creator?(obj)
    logged_in? && (current_user.id == obj.user_id)
  end

  def require_same_user
    if current_user != @user
      access_denied
    end
  end

  def access_denied
    flash[:error] = "You can't perform that action."
    if logged_in? 
      redirect_to list_user_path(current_user)
    else
      redirect_to root_path
    end
  end

  def ItemDeactivate
    flash[:notice] = "we got to item deactive"
    redirect_to :back
  end

  def current_user_has_phone
    !current_user.phone.blank?
  end

  def strip_phone_number(str)
    str.gsub(/[^0-9]/, '')
  end

  def phone_is_valid?(phone)
    strip_phone_number(phone).length == 10
  end

  def user_time_zone_offset
    if logged_in?
      @user_time_zone_offset = (Time.now.in_time_zone(current_user.time_zone).utc_offset/(60.0*60)).to_s.gsub('.',':')
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

def index
  if logged_in?
    redirect_to list_user_path(current_user)
  end
end



end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :require_user
  before_action :set_item, only: [:activate, :update, :edit, :destroy]
  before_action :require_item_creator, only: [:activate, :edit, :update, :destroy]

  def new
    @item = Item.new
  end

  def create
    # binding.pry
    params[:checkbox][:checked] == '1' ? save_time = params[:sms_time].to_datetime.change(offset: decimal_to_time_zone(params[:zone_offset])) : save_time = nil


    @item = Item.new(user: current_user, active: true, body: params[:item][:body], 
      sms_time: save_time, sms_sent: false, position: current_user.items.count+1, time_zone_offset: params[:zone_offset])
  
    if @item.save
      flash[:notice] = "New To-Do Item Added."
      redirect_to list_user_path(@item.user)
    else
      render :new
    end
  end

  def edit
    #  params[:checkbox][:checked] == '1' save date only if checked as in create
    # params[:date_changed] == true   ---> date was changed and needs to be saved.
  end

  def update
    # binding.pry
    # first update the safe parts 
    if params[:checkbox][:checked] == '0' 
      update_hash = {body: params[:item][:body], sms_time: nil}
    elsif params[:date_changed]
      update_hash = {body: params[:item][:body], sms_time: params[:sms_time].to_datetime.change(offset: decimal_to_time_zone(params[:zone_offset])), time_zone_offset: params[:zone_offset], sms_sent: false}
    end
    if @item.update(update_hash)
      flash[:notice] = "To-Do Item Updated."
      redirect_to list_user_path(@item.user)
    else
      render :edit
    end

  end


  def destroy
    flash[:error] = "Item '#{@item.body}' deleted."
    @item.destroy
    redirect_to :back
  end



  def activate
    # //toggle active status
    
    if @item.update(active: !@item.active)
      # flash[:notice]='updating'
    end

    
    # respond_to do |format|
    #   format.html do
    #     flash[:notice] = 'Why are you here?'
    #     redirect_to :back
    #   end
    #   format.js { }
    # end
  end

  def set_item
    @item = Item.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    # flash[:notice] = 'hi there'
  end

  def create
    user = User.find_by(username: params[:username])
    # binding.pry
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Welcome, #{user.username}!"
      redirect_to list_user_path(user)
    else
      flash[:error] = "There's something wrong with your username or password"
      redirect_to login_path
    end

  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out."
    redirect_to root_path
  end

  def list
    if logged_in?
      redirect_to list_user_path(current_user)
    else
      redirect_to login_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:edit, :update, :show, :list, :show]
  before_action :require_same_user, only: [:edit, :update, :list, :show]


  def new
    @user = User.new
  end

  def show

  end

  def edit

  end

  def update
    # binding.pry
    check_phone

    if @user.update(user_params)
      flash[:notice] = "Profile has been updated."
      redirect_to list_user_path(@user)
    else
      render :edit
    end
  end

  def create
    # binding.pry
    check_phone

    @user = User.new(user_params)

    if @user.save
      # flash[:notice] = "You are registered and logged in as '#{params[:user][:username]}'."
      session[:user_id] = @user.id
      redirect_to list_user_path(@user)
    else
      render :new
    end
  end

  def check_phone
    if phone_is_valid?(params[:user][:phone])
      params[:user][:phone] = strip_phone_number(params[:user][:phone])
    else
      if !params[:user][:phone].blank?
        flash[:error] = "Invalid phone number - number not saved."
      end
      params[:user][:phone] = ''
    end
  end




  def email
    send_simple_message
    @var = "something from the action"
  end

  def send_simple_message
    RestClient.post "https://api:key-d78467f903c56cbc59c84d96f21b7307"\
    "@api.mailgun.net/v2/sandboxe4171dd1b23b440ab9bf21a4b51cb487.mailgun.org/messages",
    :from => "Mailgun Sandbox <postmaster@sandboxe4171dd1b23b440ab9bf21a4b51cb487.mailgun.org>",
    :to => "owen <owen.sacafotos@gmail.com>",
    :subject => "Hello owen",
    :text => "first email with Heroku/Mailgun!  sent at #{ Time.now.in_time_zone("Pacific Time (US & Canada)") }"
  end

  def list
     # binding.pry

    @items = User.find_by(slug: params[:id]).items.order('items.position ASC')
  end

  def sort
    @items = Item.where(user_id: current_user)

    @items.each do |item|
      item.position = params['item'].index(item.id.to_s) + 1
      item.save
    end

    render :nothing => true
  end

  def user_params
    params.require(:user).permit(:username, :password, :phone)
  end

  def set_user
    @user = User.find_by(slug: params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def fix_url(str)
    str.start_with?('http://') ? str : "http://#{str}"
  end

  # def fix_datetime(dt)
    # if logged_in? and !current_user.time_zone.blank?
    #   dt = dt.in_time_zone(current_user.time_zone)
    # end
    # dt.strftime("%A %b %d %I:%M %P")
  def fix_datetime(item)  
    dt = item.sms_time.to_datetime.in_time_zone(item.time_zone_offset * -1)
    dt.strftime("%A %b %d %I:%M %P")
  end

end

app/views/home/index.html.erb
<%= link_to new_user_path do %>
<img src=<%= asset_path "listit-home-page-gfx.jpg" %> alt="easy lists and SMS reminders">
<% end %>
<div id="home-link"><%= link_to "Register to get started!", new_user_path %></div>

app/views/items/_form.html.erb
<% content_for :javascript do %>
  <%= javascript_tag do %>
    
    $(document).ready(function(){
      $('#hideMe').html(" (time: "+jstz.determine().name().replace('_',' ')+")");
      document.getElementById("offset_value").value = (new Date().getTimezoneOffset()/60) * -1;
      //var timezone = jstz.determine();
      //alert(timezone.name() + ' ' + new Date().getTimezoneOffset()/60 + ' whatwhat?');
      //d = new Date();
      //alert(new Date().addHours(-7));
      //alert(new Date(new Date().getTime() - (1000*60*60*4)));
      $(".hiddenInput").hide();
      <% if @item.sms_time != nil %>
        $('.showHideCheck').prop('checked', true);
        $(".hiddenInput").show();
      <% end %>      

      jQuery('#datetimepicker').datetimepicker({
        format:'D M d Y H:i',
        formatTime: 'g:i a',
        //value: 'Select Date and Time'
        <% if @item.sms_time != nil %>
        value: new Date ('<%= @item.sms_time.to_datetime %>'),
        onChangeDateTime:function(current_time,$input){
          document.getElementById("onChangeDate").value = 'true';
        }
        <% end %>
        //value: new Date
      });

      
      $(".showHideCheck").on("change", function() {
          if($(this).is(":checked")) {
            $(".hiddenInput").show();
          } else {
            $(".hiddenInput").hide();
          }
      });

    });
  <% end %>
<% end %>

<%= render "shared/errors", obj: @item %>

<%= form_for @item do |f| %>
  <div id='item-form'>
    <%= f.label :body, 'Description' %>
    <%= f.text_area :body, { style: "width:400px; height:60px;", maxlength: "132"} %>
  </div>
  <% if current_user_has_phone %>
    <div id='item-form'>
      <%= check_box(:checkbox, :checked, { class: 'showHideCheck', style: "display: inline-block;"}) %>
      <%= f.label :checkbox, 'Send me a text reminder', style: "display: inline-block;" %>
    </div>
    <div class='hiddenInput' id='item-form' style="display: none;">
      <%= f.label :sms_time, 'Remind me at' %>
      <%= text_field_tag :sms_time, '', { id: "datetimepicker", style: "width:300px;" } %>
      <br/><span id="hideMe" class="grey" ></span><br/>
    </div>
  <% else %>
    <div id='item-form'>
      Can't schedule reminders. No valid phone number in <%= link_to 'user settings', edit_user_path(current_user) %>.
    </div>
    <input name="checkbox[checked]" type="hidden" value="0">
  <% end %>

  <input id="offset_value" type="hidden" name="zone_offset" value="">
  <input id="onChangeDate" type="hidden" name="date_changed" value="false">
  <%= f.submit 'Do it', class: 'btn btn-primary' %>
<% end %>

app/views/items/activate.js.erb
<% if @item.active %>
  $('#item_' + <%= @item.id %> ).css("opacity",1);
<% else %>
  $('#item_' + <%= @item.id %> ).css("opacity",0.5);
<% end %>

app/views/items/edit.html.erb
<%= render 'shared/content_title', title:'Edit To-Do Item' %>
<%= render 'form' %>

app/views/items/new.html.erb
<%= render 'shared/content_title', title:'New To-Do Item' %>
<%= render 'form' %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav navbar-nav">
  <li>
    <%= link_to "Listit", root_path, :class => 'brand' %>
  </li>
  <% if logged_in? %>
    <div class='nav_item'>
      <%= link_to 'New To-Do Item', new_item_path, class: 'btn btn-success btn-small' %>
    </div>

  <div class='btn-group nav_item'>
    <%= link_to('', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown') do %>
      <%= current_user.username %>
      <span class='caret'></span>
    <% end %>
    <ul class='dropdown-menu'>
      <li>
        <%= link_to edit_user_path(current_user) do %>
          <i class='icon-pencil'></i>
          edit profile
        <% end %>
      </li>
      <li>
        <%= link_to user_path(current_user) do %>
          <i class='icon-user'></i>
          view profile
        <% end %>
      </li>
      <li>
        <%= link_to logout_path do %>
          <i class='icon-circle-arrow-left'></i>
          logout
        <% end %>
      </li>
    </ul>
  </div>

  <% else #logged out %>
  <div class='nav_item nav navbar-nav'>
      <%= link_to 'Register', register_path, class: 'btn btn-small' %>
    </div>
    <div class='nav_item nav navbar-nav'>
      <%= link_to 'Login', login_path, class: 'btn btn-success btn-small' %>
    </div>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,300' rel='stylesheet' type='text/css'>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Listit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>

  <link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/themes/smoothness/jquery-ui.css" />
  <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jstimezonedetect/1.0.4/jstz.min.js"></script>
   <script type="text/javascript">
    Date.prototype.addHours = function(h) {    
       this.setTime(this.getTime() + (h*60*60*1000)); 
       return this;   
    }
   </script>
  

  </head>

  <body>
  <%= yield :javascript %>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/shared/_content_title.html.erb
<p class='lead'>
  <%= title %>
</p>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class='alert alert-error'>
  <h6>There were some errors</h6>
  <ul>
  <% obj.errors.full_messages.each do |msg| %>
    <li><%= msg%> </li>
  <% end %>
  </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render "shared/errors", obj: @user %>

<div class="well">
  <%= form_for @user do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username %>
    <br/>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <br />
    <%= f.label :phone do %>
      U.S. Phone <span class="grey">- Optional (ex: 310 555 6789)</span>
    <% end %>
    <%= f.text_field :phone %>
    <br/>
    <%= f.submit @user.new_record? ? "Register" : "Update Profile", class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/users/edit.html.erb
<%= render 'shared/content_title', title: 'Edit User' %>

<%= render 'form' %>

app/views/users/email.html.erb
sending email.... <%= @var %><br />
<%= Time.now %>

app/views/users/index.html.erb
hello index

app/views/users/list.html.erb
<% content_for :javascript do %>
  <%= javascript_tag do %>
    function changeOpacity(id) {
      $('#item_'+id).css("opacity",0.5);
    }

    $(document).ready(function(){

      $(".checkbox").change(function() {

          $.ajax({
             url: '../../items/'+ this.id.replace("checkbox_","") + '/activate',
             type: 'POST',
             data: { remote: true },
          });
      });


      // alert('document ready');
      $('#items').sortable({
        axis: 'y',
        dropOnEmpty: false,
        handle: '.handle',
        cursor: 'crosshair',
        items: 'li',
        opacity: 0.4,
        scroll: false,
        
        update: function(){
          // alert('what what?');
          $.ajax({
          type: 'post',
          data: $('#items').sortable('serialize'),
          dataType: 'script',
          complete: function(request){
          // $('#items').effect('highlight');
        },
        url: '/users/sort'})
        }

      });
    });
  <% end %>
<% end %>
<%= render 'shared/content_title', title: 'Hi, ' + current_user.username + '!' %>
<ul id='items'> 

  <% @items.each do |item| %>
    <li id="item_<%= item.id %>" > 
      <div id="item-box" class="rounded-corners handle">
        <span id="item-check" class="checkbox-inline">
          <input class="checkbox" id="checkbox_<%= item.id %>" type="checkbox" name="activate_toggle" title="Mark as done" <% if !item.active %>checked<% end %> >
        </span>
        <span id="item-name">
          <%= item.body %>
        </span>
        <span id="item-right">
          <% if !item.sms_time.blank? %>
            <% if !item.sms_sent.blank? && item.sms_sent %>
              <span id="item-sms">
                <span class="grey">SMS:</span> Sent
              </span>
            <% else %>
              <span id="item-sms">
                <span class="grey">SMS:</span> <%= fix_datetime(item) %>
              </span>
            <% end %>
          <% end %>
          <span id="item-edit" title="Edit" >
            <%= link_to edit_item_path(item) do %>
              <span class="icon-pencil"></span>
            <% end %>
          </span>
          <span id="item-remove" title="Delete" >
            <%= link_to item_path(item), :method => :delete do %>
              <span class='icon-remove'></span>
            <% end %>
          </span>
          <% if !item.active %>
            <script type="text/javascript">
              changeOpacity(<%= item.id %>);
            </script>
          <% end %>

        </span>
      </div>
    </li>
  <% end %>

</ul>
<%= link_to new_item_path do %>
  <img src=<%= asset_path "add-items.gif" %> alt="add item">
<% end %>

app/views/users/new.html.erb
<%= render 'shared/content_title', title: 'Register new user' %>

<%= render 'form' %>

app/views/users/show.html.erb
<%= render 'shared/content_title', title: 'Show User' %>

Username: <%= @user.username %><br/>
Phone: <%= @user.phone %> <br/><br/>
<%= link_to 'Edit', edit_user_path(@user) %>